<?php
/**
 * LiveStreamApiTest
 * PHP version 8.1
 *
 * @package  Cloudinary\Video\LiveStreaming
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Video Live Streaming (Beta)
 *
 * Use the Video Live Streaming API to create and manage your RTMP live streams. This includes managing outputs as well as manually starting and stopping streams. See the [live streaming guide](https://cloudinary.com/documentation/video_live_streaming) for information on how to use the Live Streaming API to stream video to your users.    **Note**: The Live Streaming API is currently in development and is available as a Public Beta, which means we value your feedback, so please feel free to [share any thoughts with us](https://support.cloudinary.com/hc/en-us/requests/new).    The API supports Basic Authentication using your Cloudinary API Key and API Secret (which can be found on the Dashboard page of your [Cloudinary Console](https://console.cloudinary.com/pm)).
 *
 * The version of the OpenAPI document: 0.1.9
 * Contact: support@cloudinary.com
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cloudinary\Video\LiveStreaming\Test\Api;

use Cloudinary\Video\LiveStreaming\Configuration;
use Cloudinary\Video\LiveStreaming\ApiException;
use Cloudinary\Video\LiveStreaming\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LiveStreamApiTest Class Doc Comment
 *
 * @package  Cloudinary\Video\LiveStreaming
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LiveStreamApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateLiveStream
     *
     * Manually activate a live stream.
     *
     */
    public function testActivateLiveStream()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createLiveStream
     *
     * Create a new live stream.
     *
     */
    public function testCreateLiveStream()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createLiveStreamOutput
     *
     * Create a new live stream output.
     *
     */
    public function testCreateLiveStreamOutput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteLiveStream
     *
     * Delete a live stream.
     *
     */
    public function testDeleteLiveStream()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteLiveStreamOutput
     *
     * Delete a live stream output.
     *
     */
    public function testDeleteLiveStreamOutput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLiveStream
     *
     * Get a single live stream.
     *
     */
    public function testGetLiveStream()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLiveStreamOutput
     *
     * Get a single live stream output.
     *
     */
    public function testGetLiveStreamOutput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLiveStreamOutputs
     *
     * Get a list of live stream outputs.
     *
     */
    public function testGetLiveStreamOutputs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLiveStreams
     *
     * Get a list of live streams.
     *
     */
    public function testGetLiveStreams()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for idleLiveStream
     *
     * Manually idle a live stream.
     *
     */
    public function testIdleLiveStream()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateLiveStream
     *
     * Update a live stream.
     *
     */
    public function testUpdateLiveStream()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateLiveStreamOutput
     *
     * Update a live stream output.
     *
     */
    public function testUpdateLiveStreamOutput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
